# .graphclientrc.yml
sources:
  - name: BasecampSepoliaV3
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/37762/prod-base-graphbuilders/version/latest
documents:
  - ./graphql/GetUsers.gql
  - ./graphql/GetUserCredentials.gql
