# .graphclientrc.yml
sources:
  - name: BasecampSepoliaV2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/37762/basecamp-sepoliav2/version/latest
documents:
  - ./graphql/GetUsers.gql
  - ./graphql/GetUserCredentials.gql
